(add-to-list 'load-path (locate-user-emacs-file "el-get/el-get"))
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(el-get-bundle helm)
(el-get-bundle helm-ls-git)
(el-get-bundle grep-a-lot)
(el-get-bundle auto-complete)
(el-get-bundle auto-complete-clang-async)
(el-get-bundle init-loader)
(el-get-bundle web-mode)
(el-get-bundle magit)
(el-get-bundle elixir-mode)
(el-get-bundle qml-mode)
(el-get-bundle adoc-mode)
(el-get-bundle anzu)
(el-get-bundle auto-highlight-symbol)
(el-get-bundle pkg-info)
(el-get-bundle elscreen)
(el-get-bundle yasnippet)
