(add-to-list 'load-path (locate-user-emacs-file "el-get/el-get"))
(unless (require 'el-get nil 'noerror)
  (with-current-buffer
      (url-retrieve-synchronously
       "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
    (goto-char (point-max))
    (eval-print-last-sexp)))

(el-get-bundle helm)
(el-get-bundle helm-ls-git)
(el-get-bundle grep-a-lot)
(el-get-bundle company-mode)
(el-get-bundle irony-mode)
(el-get-bundle irony-eldoc)
(el-get-bundle company-irony)
(el-get-bundle init-loader)
(el-get-bundle web-mode)
(el-get-bundle magit)
(el-get-bundle qml-mode)
(el-get-bundle adoc-mode)
(el-get-bundle anzu)
(el-get-bundle auto-highlight-symbol)
(el-get-bundle pkg-info)
(el-get-bundle elscreen)
(el-get-bundle yasnippet)
(el-get-bundle puml-mode)
(el-get-bundle redo+)
(el-get-bundle recentf-ext)
(el-get-bundle emmet-mode)
(el-get-bundle migemo)
(el-get-bundle csharp-mode)
(el-get-bundle tuareg-mode)
(el-get-bundle utop)
(el-get-bundle iedit)
(el-get-bundle merlin)
(el-get-bundle alchemist)
